### ISSUE TITLE
[Feature Request] add option for sorting downloads in folders (Artist/Album Title) and to have an option to disable the Quality folder (ie FLAC (24bit-44.1kHz))

### ISSUE THREAD

**Issue by JosefAschauer** [DJDoubleD/QobuzDownloaderX-MOD#75] opened 2024-01-29 12:24 UTC
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

would be great to get a setting to structure the downloads in diectories and subfolders, ie  mainfolder Artist and an Album subfolder for each Album. Additionally it would be great to have an option to disable the quality subfolders (ie FLAC (24bit-44.1kHz)) 

---

## **Describe the solution you'd like**

*

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

You've done a great job!

**Comment by DJDoubleD** [comment] 2024-01-29 14:07
This is a duplicate of #24

**Closed by DJDoubleD** 2024-01-29 14:07 UTC
Labels: duplicate
