### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by DanniXDna** [DJDoubleD/QobuzDownloaderX-MOD#82] opened 2024-04-02 21:28 UTC
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* I wish to have lyrics embed into my music.

---

## **Describe the solution you'd like**

* An implementation of lyrics to the songs from services like Musixmatch for synchronized lyrics or Genius for normal lyrics.
---

## **Describe alternatives you've considered**

* Other Lyrics services idk,

---

### **Additional context**

*

**Comment by orbittwz** [comment] 2024-04-04 06:51
dupe of #63 ??

**Comment by DJDoubleD** [comment] 2024-04-08 00:00
This is indeed a duplicate of #63.
I'll close this one and add a link to this issue in #63 just for reference.

**Closed by DJDoubleD** 2024-04-08 00:00 UTC
Labels: duplicate
