### ISSUE TITLE
[Bug] Track is not available for streaming. Unable to download.

### ISSUE THREAD

**Issue by Astroamadeus** [DJDoubleD/QobuzDownloaderX-MOD#90] opened 2024-06-15 21:08 UTC
# **🐞 Bug Report**

## **Describe the bug**
Some tracks cause the following error when trying to download them, despite the fact that such tracks can be played and listened to in the regular windows app or in the web player: [_EDIT: After careful verification, those tracks can only be played for 30 seconds_]

```
2024-06-15 22:43:49.618 : =============================================================
2024-06-15 22:43:49.619 : Downloading <Track> from https://open.qobuz.com/track/3916868
2024-06-15 22:43:49.619 : =============================================================

2024-06-15 22:43:49.625 : Grabbing Track info...
2024-06-15 22:43:49.944 : Track "Ravel: Menuet sur le nom de HAYDN" found. Starting Download...

2024-06-15 22:43:49.948 : Track 1 Ravel: Menuet sur le nom de HAYDN is not available for streaming. Unable to download.
```

*

---

### **Is this a regression?**
I don't know

---

### **To Reproduce**

Try to download a track that has the " (i) " mouse hover button greyed out. For example the tracks:
6. [https://play.qobuz.com/track/3916868](https://play.qobuz.com/track/3916868) or
12. [https://play.qobuz.com/track/3916865](https://play.qobuz.com/track/3916865)
in the following album:
[https://play.qobuz.com/album/0002894767906](https://play.qobuz.com/album/0002894767906)

---

### **Expected behaviour**
Expected behaviour is that the track should be downloaded since the track **_can_** be played and listened to in the regular Windows desktop app or in the Qobuz web player. [_EDIT: After careful verification, those tracks can only be played for 30 seconds_]

*

---

### **Screenshots**
N/A

---

### **Additional context**
N/A

*

**Comment by DJDoubleD** [comment] 2024-06-15 23:33
The [example album](https://play.qobuz.com/album/0002894767906) you give, is first of all region restricted,
Can you tell me the country of your account that allows you to play the **_COMPLETE_** tracks that are grayed out in the qobuz app for your example album?

For me, the grayed out tracks will only play 30 second previews in the Qobuz web player.
That's why these greyed out tracks are considered as not available for streaming and are skipped by the application.

**Comment by Astroamadeus** [comment] 2024-06-16 07:31
> The [example album](https://play.qobuz.com/album/0002894767906) you give, is first of all region restricted, Can you tell me the country of your account that allows you to play the **_COMPLETE_** tracks that are grayed out in the qobuz app for your example album?
> 
> For me, the grayed out tracks will only play 30 second previews in the Qobuz web player. That's why these greyed out tracks are considered as not available for streaming and are skipped by the application.

Hi @DJDoubleD,
Thanks for your reply.
My account was created in France. _**BUT**_, now you mention it, the couple of problematic tracks in this album that are greyed out are indeed limited to 30 seconds in the windows app or the web app. All the other tracks play in full however.
I guess the problem is with Qobuz then.
In any case, thank you for your amazing work on QBDLX-MOD.

**Comment by DJDoubleD** [comment] 2024-06-16 10:49
Closing since this behavior is _works as designed_

**Closed by DJDoubleD** 2024-06-16 10:49 UTC
Labels: invalid
