### ISSUE TITLE
[Bug] Not downloading full files, only 30 second clips

### ISSUE THREAD

**Issue by realjohnpork** [DJDoubleD/QobuzDownloaderX-MOD#59] opened 2023-10-21 20:24 UTC
# **🐞 Bug Report**
Program is only downloading 30 second clips
## **Describe the bug**
 
Only the first 30 seconds are being downloaded.
*

---

### **Is this a regression?**

Yes, this did not happen as of around 3 months ago.

### **To Reproduce**

1. Download an album
2. Experience error

---

### **Expected behaviour**

The files downloaded should be full and complete.

---

### **Screenshots**

---

### **Additional context**

*

**Comment by orbittwz** [comment] 2023-10-22 07:01
did you connect with your Qobuz account and it's not free account?

**Comment by DJDoubleD** [comment] 2023-10-22 13:08
> # **🐞 Bug Report**
> Program is only downloading 30 second clips

This is not a bug, it just means you are using an account with an expired subscription so you can only stream 30 second previews.
Solution is simply to login with an account with an active subscription and not an expired one, as @orbittwz pointed out.
Closing issue.

**Closed by DJDoubleD** 2023-10-22 13:08 UTC
