### ISSUE TITLE
[Bug] Issue logging into to QobuzDownloaderX-MOD 1.2.5.0

### ISSUE THREAD

**Issue by HandsomeTopKhi** [DJDoubleD/QobuzDownloaderX-MOD#98] opened 2024-08-16 08:58 UTC
# **🐞 Bug Report**

## **Describe the bug**

*Hello I have been using QobuzDownloaderX-MOD 1.2.5.0 since a year now with no issues. Suddenly I started getting this error whenever I try to login to the QobuzDownloaderX-MOD 1.2.5.0 app. I get this error no matter how many times I try to login.
This is some .NET Framework error which I don't seem to understand. 

https://ptpimg.me/tpq1j1.png

Please help !!!! I'm panicking I have never faced any such issue with Qbdlx before. 

**THIS IS THE WHOLE TEXT IN THE ERROR**
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at QobuzDownloaderX.QobuzDownloaderX.MainForm_Load(Object sender, EventArgs e) in D:\a\QobuzDownloaderX-MOD\QobuzDownloaderX-MOD\QobuzDownloaderX\View\MainForm.cs:line 74
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
QobuzDownloaderX
    Assembly Version: 1.2.5.0
    Win32 Version: 1.2.5.0
    CodeBase: file:///S:/QBDLX-MOD_1.2.5.0/QobuzApiSharp.DLL0/QobuzDownloaderX.exe
----------------------------------------
PortableJsonSettingsProvider
    Assembly Version: 0.2.2.0
    Win32 Version: 0.2.2.0
    CodeBase: file:///S:/QBDLX-MOD_1.2.5.0/QobuzApiSharp.DLL0/PortableJsonSettingsProvider.DLL
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///S:/QBDLX-MOD_1.2.5.0/QobuzApiSharp.DLL0/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9241.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9214.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
QobuzApiSharp
    Assembly Version: 0.0.7.0
    Win32 Version: 0.0.7.0
    CodeBase: file:///S:/QBDLX-MOD_1.2.5.0/QobuzApiSharp.DLL0/QobuzApiSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

---

### **Is this a regression?**

---

### **To Reproduce**

* The app to work normally

---

### **Screenshots**

--- https://ptpimg.me/tpq1j1.png

### **Additional context**

* This error started today. Maybe Microsoft has updated something in windows 10 which is causing this error.

**Comment by MikevE1995** [comment] 2024-08-16 14:22
I'm having the same issues

**Comment by MikevE1995** [comment] 2024-08-16 14:23
@DJDoubleD

**Comment by MikevE1995** [comment] 2024-08-16 14:28
What worked for me was switching to a different Qobuz login

**Comment by DJDoubleD** [comment] 2024-08-16 15:20
This is a duplicate of #87, which I still have not been able to reproduce...
@HandsomeTopKhi: Since you get the error when logging in and @MikevE1995 says he also experienced the error but only with a specific account (as switching accounts solved it), can you please tell me:

1) Are you using the normal email/pwd login or the id/token login?
2) If by any chance you are using the id/token method and it's a public account, could you share the id/token combination which produces the error? 
3) Can you try different accounts (e.g. find some [here](https://rentry.co/firehawk52#qobuz-tokens)) and see if you experience the error with other accounts as well?
4) If you are using a private account, did you check that the account is still active and if anything changed to it's subscription status today?

Sadly, as long as I'm not able to reproduce the error, I won't be able to solve it.

**Comment by HandsomeTopKhi** [comment] 2024-08-17 02:05
1. I'm using  id/token login method
2. id: 2635874	Token: S3RT4gfZdNKD7tUk9t8tazANQxDZy6wD70EKW0smholQH8dku7OQeluMOiDiE_38zhZFxhOj1HMD0fxYQ993iw
3. Ok I tried another Id/Token and it worked looks like this specific id/token has some issues.

Thank you MikevE1995 & DJDoubleD for the help. We should mention this somewhere that if you face such issue we should used a different account from here https://rentry.co/firehawk52#qobuz-tokens to resolves this. I wasted around 6 hours yesterday due to this and also installed .Net Framework and it's updates multiple times. Even uninstalled a few recent windows updates to troubleshoot this and in the end it was a simply change of account to make it work.

**Comment by orbittwz** [comment] 2024-08-17 06:39
@DJDoubleD can you please remove the link here and all worded references here?? it's not a good thing to mention this here

**Comment by orbittwz** [comment] 2024-08-17 06:39
same for #87

**Comment by HandsomeTopKhi** [comment] 2024-08-17 06:43
> @DJDoubleD can you please remove the link here and all worded references here?? it's not a good thing to mention this here

Removed. I mentioned them since I was asked about them in the following post.

**Comment by orbittwz** [comment] 2024-08-17 06:50
Thank you!
As a general rule for everyone watching this, don't mention anything you want to keep for yourself :)

**Closed** 2024-08-17 13:59 UTC
Labels: bug, duplicate
