### ISSUE TITLE
add an option to not create the bitrate subfolder for downloads

### ISSUE THREAD

**Issue by JosefAschauer** [DJDoubleD/QobuzDownloaderX-MOD#110] opened 2024-10-15 17:08 UTC
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

Currently each download creates a subdolder, ie FLAC (16bit-44.1kHz) - which I want to avoid
*

---

## **Describe the solution you'd like**

I'd like a checkbox to avoid this
*

---

## **Describe alternatives you've considered**

anything which works, even manual editing of the template used is an option
*

---

### **Additional context**

*

**Comment by DJDoubleD** [comment] 2024-10-15 17:47
I'm closing this as it is basically a duplicate of what's asked in #24, #29 & #36

**Closed by DJDoubleD** 2024-10-15 17:47 UTC
Labels: duplicate
